<change> 805cde14 46800000 # Next four are RTOC constants used for MaxPositiveVerticalVelocity
<change> 805cde18 46800000 # Allows player to fall at very high speeds, number somewhat arbitrary
<change> 805cde1c 46800000
<change> 805cde24 46800000
<change> 805cde28 46800000
<change> 80144a78 480008c4 # skip over water damping
<cvar> airaccelerate_mul f32
<cvar> accelerate_mul f32
<cvar> max_walk_speed f32
<cvar> friction_mul f32
<cvar> airaccelerate_wishspeed_clamp f32
<cvar> jump_impulse f32
<cvar> gravity_mul f32
<cvar> input_wishspeed f32
<cvar> stop_speed f32
<cvar> underwater_movement_depth f32
<cvar> leniency_ticks i32
<cvar> crouch_height f32
<trampoline> hooked_computemove 8015e4b0
<callgate> _callgate_table _mod_dispatch_table _callgate_dispatch _trampoline_restore_table
<cleanup> release_mod shutdown_signal 800063d8
<elf> source_movement_mp2_trilogy.elf
