<change> 8041a568 46800000 # Next four are RTOC constants used for MaxPositiveVerticalVelocity
<change> 8041a56c 46800000 # Allows player to fall at very high speeds, number somewhat arbitrary
<change> 8041a570 46800000
<change> 8041a574 46800000
<change> 80015684 480004a8 # skip over water damping
<cvar> airaccelerate_mul f32
<cvar> accelerate_mul f32
<cvar> max_walk_speed f32
<cvar> friction_mul f32
<cvar> airaccelerate_wishspeed_clamp f32
<cvar> jump_impulse f32
<cvar> gravity_mul f32
<cvar> input_wishspeed f32
<cvar> stop_speed f32
<cvar> underwater_movement_depth f32
<cvar> leniency_ticks i32
<cvar> screwattack_max_drop f32
<cvar> screwattack_extra_starting_height f32
<cvar> gravboost_force f32
<cvar> crouch_height f32
<cvar> crouch_max_speed_damp f32
<cvar> rocket_blast_radius f32
<cvar> rocket_velocity_multiplier f32
<cvar> rocket_jump_base_speed f32
<cvar> rocket_jump_speed_falloff_max f32
<cvar> rocket_jump_speed_falloff_min f32
<cvar> rocket_jump_max_damage f32
<cvar> side_dash_impulse f32
<cvar> side_dash_jump_height_reduction f32
<vthook> hooked_energyprojectile_think 803b2fe0
<trampoline> hooked_computemovement 801883ec
<callgate> _callgate_table _mod_dispatch_table _callgate_dispatch _trampoline_restore_table
<cleanup> release_mod shutdown_signal 800063d8
<elf> source_movement_mp2.elf
